// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxkQPBI6qdvcwqJCydIca6VdC60e4G3I',
    appId: '1:770603213771:android:49e90ce240376ab705cc4e',
    messagingSenderId: '770603213771',
    projectId: 'learn-flutter-64271',
    databaseURL: 'https://learn-flutter-64271-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-flutter-64271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Vee9QsT3ZhSdIHxZ8dOyBpPQjPMYZNU',
    appId: '1:770603213771:ios:8a4e760a7e8c4d6e05cc4e',
    messagingSenderId: '770603213771',
    projectId: 'learn-flutter-64271',
    databaseURL: 'https://learn-flutter-64271-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-flutter-64271.appspot.com',
    iosBundleId: 'com.vengeang.chatApp',
  );
}
